---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gatewayclass
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway
  namespace: mern-devops
spec:
  gatewayClassName: envoy-gatewayclass
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      # optional: hostnames: ["example.com"]
      # allowedRoutes: omitted => default allows same-namespace routes

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mern-route
  namespace: mern-devops
spec:
  parentRefs:
    - name: envoy-gateway   # name of Gateway created above
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"             # matches root and all subpaths
      backendRefs:
        - name: frontend-service
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: "/books"        # matches /books and subpaths
      backendRefs:
        - name: backend-service
          port: 8000